# pytest.ini
[pytest]


disable_test_id_escaping_and_forfeit_all_rights_to_community_support = True
addopts = -vs --tb=short --show-capture=all

#Enable command-line logging
#log_cli = true
#log_cli_level = DEBUG

#Capture all loggers, including third-party libraries
#log_cli_format = %(asctime)s [%(levelname)s] %(name)s: %(message)s

#Key: Set up log propagation to ensure that all loggers output to the root logger
#log_auto_indent = true