from pymycobot import MyCobot280

mc = MyCobot280("COM25",debug=1)
mc.power_on()
# mc.power_off()
# mc.power_off()
# mc.is_power_on()
# mc.go_home()
print(type(None))
# mc.release_all_servos()
# mc.focus_all_servos()
# mc.send_coord(6,100,10)
# mc.send_angles([0,20,-90,-20,0,0],10)
# print(mc.get_modify_version())
# print(mc.get_basic_version())
# print(mc.get_system_version())
# print(mc.get_coords())
# mc.send_coord(3,150,10)
# mc.clear_error_information()
# print(mc.get_error_information())
# mc.release_all_servos()
# while 1:
#     print(mc.get_angles())