import time
from time import sleep

from pymycobot import MyCobot280


mc = MyCobot280("COM12",debug=1)
# mc.send_angles()
# mc.send_angles([50,50,50,50,50,50],20)
# mc.release_all_servos()
# while 1:
#     print(mc.get_angles())
#     time.sleep(1)
# mc.set_encoder(1,3980,10)
# sleep(5)
# print(mc.get_encoder(5))
# print(mc.get_angles())
# mc.set_joint_min(1,150)
# mc.set_joint_min(1,-168)
# # print(mc.get_joint_min_angle(1))
# print(mc.get_joint_max_angle(1))
# print(mc.get_joint_min_angle(1))
mc.set_fresh_mode(1)
mc.send_angle(1,-160,10)
sleep(2)
mc.joint_brake(1)
# mc.send_angles([0,20,-90,-20,0,0],50)
# angles = mc.get_angles()
# print(mc.is_in_position(angles, 0))

# mc.send_coords([128.8, -62.2, 227.7, 178.42, -0.28, -90.08],50)
# time.sleep(5)
# coords = mc.get_coords()
# print(coords)
# print(mc.is_in_position(coords,1))
# print(angles)
# mc.send_angles(angles,20)
# print(mc.get_angles())
# mc.send_angle(4,150,30)
# mc.init_gripper()
# print(mc.get_HTS_gripper_torque())
# print(mc.get_gripper_protect_current())
# sleep(5)
# mc.set_encoder(1,149,10)
# print(mc.get_angles())
# print(mc.get_encoder(1))
# print(mc.get_servo_data(7,1))
# print(mc.get_radians())
# print(mc.get_servo_data(2,4))
# print(mc.get_servo_data(7,0))

# mc.send_coords([103.4, -62.0, 280, 180, 0.71, -88.87],10)
# print("coord:",mc.get_coords())
# mc.power_on()
# mc.power_off()
# mc.power_off()
# mc.is_power_on()
# mc.go_home()
# print(type(None))
# mc.release_all_servos()
# mc.focus_all_servos()
# mc.send_coord(6,100,10)
# mc.send_angles([0,20,-90,-20,0,0],10)
# print(mc.get_modify_version())
# print(mc.get_basic_version())
# print(mc.get_system_version())
# print(mc.get_coords())
# mc.send_coord(3,150,10)
# mc.clear_error_information()
# print(mc.get_error_information())
# mc.release_all_servos()
# while 1:
#     print(mc.get_angles())